apps/smakolyk/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import (
    HistorySetterAjaxView,
    HistoryView,
    HomePageView,
    OrderView,
    PriceSetterAjaxView,
    TotalAmountCounterAjaxView,
)

app_name = "smakolyk"

urlpatterns = [
    path("", TemplateView.as_view(template_name="welcome.html"), name="welcome"),
    path("smakolyk/", HomePageView.as_view(), name="home"),
    path("create-order/", OrderView.as_view(), name="order"),
    path(
        "order-error/",
        TemplateView.as_view(template_name="order_error.html"),
        name="order_error",
    ),
    path(
        "success-order/",
        TemplateView.as_view(template_name="order_success.html"),
        name="order_success",
    ),
    path("set-price/", PriceSetterAjaxView.as_view(), name="set_price"),
    path(
        "set-total-price/", TotalAmountCounterAjaxView.as_view(), name="set_total_price"
    ),
    path("history/", HistoryView.as_view(), name="history"),
    path("get-history-week/", HistorySetterAjaxView.as_view(), name="get_history_week"),
    path(
        "order-access-denied/",
        TemplateView.as_view(template_name="access_denied_order.html"),
        name="weekend",
    ),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.smakolyk.urls")),
    path("", include("apps.user.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/smakolyk/forms.py
from django import forms
from django.db import transaction
from django.utils import timezone

from .models import History, Order
from .utils import get_menu_choices, get_order_data, get_order_total
from .values import FormDefaultValues, ViewSettingValues


class DisabledOptionWidget(forms.Select):
    def render(self, name, value, attrs=None, renderer=None):
        html_code = super(DisabledOptionWidget, self).render(
            name, value, attrs, renderer
        )
        html_code = html_code.replace(
            '<option value=""', '<option value="------" disabled'
        )

        return html_code


class OrderForm(forms.ModelForm):
    first_course = forms.ChoiceField(required=False, widget=DisabledOptionWidget)
    first_course_quantity = forms.IntegerField(min_value=0, required=False)
    second_course = forms.ChoiceField(required=False, widget=DisabledOptionWidget)
    second_course_quantity = forms.IntegerField(min_value=0, required=False)
    dessert = forms.ChoiceField(required=False, widget=DisabledOptionWidget)
    dessert_quantity = forms.IntegerField(min_value=0, required=False)
    drink = forms.ChoiceField(required=False, widget=DisabledOptionWidget)
    drink_quantity = forms.IntegerField(min_value=0, required=False)
    date = forms.DateField(required=False)

    class Meta:
        model = Order
        fields = ViewSettingValues.ORDER_FORM_FIELDS

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)

        self.user = self.initial.get("user", None)

        # I'm altering choices dynamically, so there won't be any error on running `makemigrations` command
        self.fields["first_course"].choices = get_menu_choices("first_course")
        self.fields["second_course"].choices = get_menu_choices("second_course")
        self.fields["dessert"].choices = get_menu_choices("dessert")
        self.fields["drink"].choices = get_menu_choices("drink")

    def save(self, commit=True):
        with transaction.atomic():
            order = self.create_order_object()
            order.save()

            order_data = get_order_data(order)
            total_amount = get_order_total(order_data)

            self.create_history_object(order, total_amount, order_data)

            return order, order_data, total_amount

    def create_order_object(self) -> Order:
        """
        A method that creates an Order object.
        :return: Order object
        """
        return Order(
            user=self.user,
            date=self.cleaned_data.get("date") or timezone.now().date(),
            first_course=self.cleaned_data.get("first_course")
            or FormDefaultValues.DISH_NOT_CHOSEN_DEFAULT_VALUE,
            first_course_quantity=self.cleaned_data.get("first_course_quantity")
            or FormDefaultValues.DISH_QUANTIRY_NOT_CHOSEN_DEFAULT_VALUE,
            second_course=self.cleaned_data.get("second_course")
            or FormDefaultValues.DISH_NOT_CHOSEN_DEFAULT_VALUE,
            second_course_quantity=self.cleaned_data.get("second_course_quantity")
            or FormDefaultValues.DISH_QUANTIRY_NOT_CHOSEN_DEFAULT_VALUE,
            dessert=self.cleaned_data.get("dessert")
            or FormDefaultValues.DISH_NOT_CHOSEN_DEFAULT_VALUE,
            dessert_quantity=self.cleaned_data.get("dessert_quantity")
            or FormDefaultValues.DISH_QUANTIRY_NOT_CHOSEN_DEFAULT_VALUE,
            drink=self.cleaned_data.get("drink")
            or FormDefaultValues.DISH_NOT_CHOSEN_DEFAULT_VALUE,
            drink_quantity=self.cleaned_data.get("drink_quantity")
            or FormDefaultValues.DISH_QUANTIRY_NOT_CHOSEN_DEFAULT_VALUE,
        )

    @staticmethod
    def create_history_object(
        order: Order, total_amount: int, order_data: dict
    ) -> None:
        """
        A method that creates a History object.
        :param order: Order object
        :param total_amount: int
        :param order_data: dict
        :return: None
        """
        History.objects.create(
            user=order.user,
            date=order.date,
            total_amount=total_amount,
            first_course=order.first_course,
            first_course_quantity=order.first_course_quantity,
            first_course_price=order_data.get("first_course_price"),
            second_course=order.second_course,
            second_course_quantity=order.second_course_quantity,
            second_course_price=order_data.get("second_course_price"),
            dessert=order.dessert,
            dessert_quantity=order.dessert_quantity,
            dessert_price=order_data.get("dessert_price"),
            drink=order.drink,
            drink_quantity=order.drink_quantity,
            drink_price=order_data.get("drink_price"),
        )

apps/smakolyk/views.py
import json
from datetime import date, datetime, timedelta

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import formset_factory
from django.http import (
    HttpResponseBadRequest,
    HttpResponsePermanentRedirect,
    HttpResponseRedirect,
    JsonResponse,
)
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.views.generic import CreateView, TemplateView

from apps.user.models import CustomUser

from .forms import OrderForm
from .models import History, Menu, Order
from .utils import (
    get_current_week_dates,
    get_dates_dict,
    get_days_dict,
    notify_about_oversum,
)
from .values import DataMappingValues, ViewSettingValues


class HomePageView(CreateView):
    template_name = "home.html"

    def get(self, request, *args, **kwargs):
        menu: dict[str, list] = dict()

        for field_name in DataMappingValues.dish_field_names:
            dishes = Menu.objects.values_list(field_name, flat=True)
            # Splitting dishes into chunks
            menu[field_name] = [
                dishes[i : i + ViewSettingValues.CHUNK_MENU_SIZE]
                for i in range(0, len(dishes), ViewSettingValues.CHUNK_MENU_SIZE)
            ]

        return render(
            request,
            self.template_name,
            {
                "menu": menu,
                "has_order": History.objects.filter(user_id=request.user.id).exists(),
            },
        )


class OrderView(LoginRequiredMixin, CreateView):
    login_url = "login"
    template_name = "order.html"
    success_url = "smakolyk:order_success"
    model = Order
    formset = formset_factory(
        form=OrderForm,
        extra=ViewSettingValues.FORMS_NUMBER,
    )

    def get(self, request, *args, **kwargs):
        if result := self.check_page_accessibility():
            return result

        formset = self.formset()
        days = get_days_dict()

        return render(
            request,
            self.template_name,
            context={"formset": formset, "days": days, **get_dates_dict()},
        )

    def post(self, request, *args, **kwargs):
        formset = self.formset(
            request.POST,
            initial=[{"user": request.user}] * ViewSettingValues.FORMS_NUMBER,
        )

        if formset.is_valid():
            for form in formset:
                order, order_data, total_amount = form.save()

                if total_amount > ViewSettingValues.MAX_ORDER_AMOUNT:
                    user = get_object_or_404(CustomUser, id=request.user.id)
                    oversum = total_amount - ViewSettingValues.MAX_ORDER_AMOUNT

                    notify_about_oversum(
                        user=user, oversum=oversum, order_date=order.date
                    )

            return redirect(self.success_url)

        [messages.error(request, error) for error in formset.errors]
        return render(
            request,
            self.template_name,
            context={"formset": formset, "days": get_days_dict(), **get_dates_dict()},
        )

    def check_page_accessibility(
        self,
    ) -> None | HttpResponsePermanentRedirect | HttpResponseRedirect:
        """
        Checks if the user has access to the page.
        :return: None
        """
        if self.order_exists_for_the_next_week():
            return redirect("smakolyk:order_error")

        if self.is_weekend():
            return redirect("smakolyk:weekend")

    def order_exists_for_the_next_week(self) -> bool:
        """
        Check if order exists for current week
        :return: bool
        """
        dates = get_current_week_dates()

        for date_ in dates:
            if Order.objects.filter(date=date_, user_id=self.request.user.id).exists():
                return True

        return False

    @staticmethod
    def is_weekend() -> bool:
        """
        Checks if today it's weekend
        :return: bool
        """
        return datetime.now().weekday() > ViewSettingValues.FRIDAY_WEEKDAY_NUMBER or (
            datetime.now().weekday() >= ViewSettingValues.FRIDAY_WEEKDAY_NUMBER
            and datetime.now().time().hour >= ViewSettingValues.WEEKEND_START_HOUR
        )


class PriceSetterAjaxView(View):
    def get(self, request, *args, **kwargs):
        menu = dict()

        for dish_field_name, dish_price_field_name in zip(
            DataMappingValues.dish_field_names, DataMappingValues.dish_price_field_names
        ):
            menu.update({dish_field_name: dict()})

            for dish, price in zip(
                list(Menu.objects.values_list(dish_field_name, flat=True)),
                list(Menu.objects.values_list(dish_price_field_name, flat=True)),
            ):
                menu[dish_field_name].update({dish: price})

        return JsonResponse({"response": menu})


class TotalAmountCounterAjaxView(View):
    total_amount = ViewSettingValues.MAX_ORDER_AMOUNT

    def post(self, request, *args, **kwargs):

        try:
            data = json.loads(request.body)
        except json.JSONDecodeError:
            return JsonResponse(
                {"error": "Invalid JSON"}, status=HttpResponseBadRequest.status_code
            )

        dish_quantities = [
            self._get_value(field_name, data)
            for field_name in DataMappingValues.dish_quantity_field_names
        ]
        dish_prices = [
            self._get_value(field_name, data)
            for field_name in DataMappingValues.dish_price_field_names
        ]

        result = self.total_amount - sum(
            [price * quantity for price, quantity in zip(dish_prices, dish_quantities)]
        )

        return JsonResponse(
            {
                "response": result,
                "amount_deducted": result < ViewSettingValues.MIN_ORDER_VALUE,
            }
        )

    @staticmethod
    def _get_value(field_name: str, data: dict) -> int:
        """
        Get price from request.POST
        :param field_name: str
        :param data: dict
        :return: int
        """
        return int(data.get(f"{field_name}", ViewSettingValues.MIN_ORDER_VALUE))


class HistoryView(TemplateView):
    template_name = "history.html"

    def get(self, request, *args, **kwargs):
        current_week_days = self.get_current_week_days()

        if History.objects.filter(date=next(iter(current_week_days))).exists():
            data = {
                weekday: History.objects.get(
                    date=current_week_days[idx], user_id=request.user.id
                )
                for idx, weekday in enumerate(ViewSettingValues.WEEKDAY_NAMES)
            }

        else:
            next_week_days = self.get_next_week_days()

            data = {
                weekday: History.objects.get(
                    date=next_week_days[idx], user_id=request.user.id
                )
                for idx, weekday in enumerate(ViewSettingValues.WEEKDAY_NAMES)
            }

        return render(request, self.template_name, {"data": data})

    @staticmethod
    def get_current_week_days() -> list[date]:
        """
        Returns current week days
        :return: list[date]
        """
        today = date.today()
        current_weekday_number = today.weekday()
        start_of_the_week = today + timedelta(days=0 - current_weekday_number)

        return [(start_of_the_week + timedelta(days=i)) for i in range(5)]

    @staticmethod
    def get_next_week_days() -> list[date]:
        """
        Returns next week days
        :return: list[date]
        """
        today = date.today()
        current_weekday = today.weekday()
        start_of_week = today + timedelta(days=7 - current_weekday)

        return [(start_of_week + timedelta(days=i)) for i in range(5)]


class HistorySetterAjaxView(View):
    def get(self, request, *args, **kwargs):
        chosen_date = request.GET.get("date")

        if not History.objects.filter(date=chosen_date).exists():
            return JsonResponse({"date_exists": False})

        week_dates = self.get_dates_in_week(chosen_date)
        history_data = dict()

        for idx, weekday_name in enumerate(ViewSettingValues.WEEKDAY_NAMES):
            history_object = History.objects.filter(
                date=week_dates[idx], user_id=request.user.id
            ).first()
            history_data[weekday_name.lower()] = dict()

            for field_name in ViewSettingValues.HISTORY_OBJECT_FIELDS:
                field_value = getattr(history_object, field_name)

                history_data[weekday_name.lower()][field_name] = field_value

        return JsonResponse({"history_data": history_data, "date_exists": True})

    @staticmethod
    def get_dates_in_week(date_: str) -> list[str]:
        """
        Returns a list of dates that are present in the same week with `date_`
        :param date_: str
        :return: list[str]
        """
        formated_date = datetime.strptime(date_, "%Y-%m-%d").date()
        start_of_week = formated_date - timedelta(days=formated_date.weekday())

        return [
            (start_of_week + timedelta(days=i)).strftime("%Y-%m-%d") for i in range(5)
        ]

apps/smakolyk/templates/access_denied_order.html
{% extends 'base.html' %}
{% load static %}

{% block extrahead %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="{% static 'css/order_error.css' %}">
<link
    type="image/png"
    rel="Shortcut Icon"
    href="{% static 'image/pizza.png' %}">
  <title>Error</title>
{% endblock %}

{% block content %}
<body>
    <div class="container">
        <div class="circle">
          <i class="fa-solid fa-xmark"></i>
        </div><br>
        <div class="thx">Error!</div><br>
        <div class="details">You have to complete your order between Monday 8 AM <br> and Friday 18 PM ! <br> Please try next week!</div>
        <button class="oke"><a href="{% url 'smakolyk:home' %}" style="text-decoration:none; color: white;">OK</a></button>
    </div>


  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
  </script>
{% endblock %}

apps/smakolyk/templates/history.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block extrahead %}
  <link rel="stylesheet" href="{% static 'css/history.css' %}">
  <link
  type="image/png"
  rel="Shortcut Icon"
  href="{% static 'images/pizza.png' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
  integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <title>History</title>
    <style>
      body {
        background-image: url('{% static "images/bg.jpg" %}');
        background-size: cover;
      }
    </style>
{% endblock  %}


{% block content %}

<nav>
  <div class="logo">
    <div class="home"><a style="text-decoration:none;color:white;" href='{% url "smakolyk:home" %}'>Home</a></div>
    <h1>
      <img class="img1" src="{% static 'images/pizza.png' %}">
      SMAKOLYK
      <img src="{% static 'images/pizza.png' %}">
    </h1>
  </div>
</nav>
  <div class="upper">
      <ul>
          <li><input id='date' type="date"></li>
          <li>History</li>
          <li><div id='total'>Total : </div></li>
      </ul>
  </div>
  <table>
      <tr>
          <th>Day</th>
          <th>Course</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Total for day</th>
      </tr>
      {% for key, item in data.items %}
        <tr>
            <td>{{ key }}</td>

            <td>
                <div id="{{ key | lower }}-first_course">{{ item.first_course }}</div>
                <div id='{{ key | lower }}-second_course'>{{item.second_course}}</div>
                <div id='{{ key | lower }}-dessert'>{{item.dessert}}</div>
                <div id='{{ key | lower }}-drink'>{{item.drink}}</div>
            </td>
            <td>
                <div id='{{ key | lower }}-first_course_price'>{{ item.first_course_price }}</div>
                <div id='{{ key | lower }}-second_course_price'>{{item.second_course_price}}</div>
                <div id='{{ key | lower }}-dessert_price'>{{item.dessert_price}}</div>
                <div id='{{ key | lower }}-drink_price'>{{item.drink_price}}</div>
            </td>
            <td>
                <div id='{{ key | lower }}-first_course_quantity'>{{item.first_course_quantity}}</div>
                <div id='{{ key | lower }}-second_course_quantity'>{{item.second_course_quantity}}</div>
                <div id='{{ key | lower }}-dessert_quantity'>{{item.dessert_quantity}}</div>
                <div id='{{ key | lower }}-drink_quantity'>{{item.drink_quantity}}</div>
            </td>
            <td>
                <div id='{{ key | lower }}-total-amount' title="total-amount" >{{item.total_amount}}</div>
            </td>
        </tr>
      {% endfor %}
    </table>
    <script src='{% static "js/history.js" %}'></script>
{% endblock content %}

apps/smakolyk/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block extrahead %}
    <link
    type="image/png"
    rel="Shortcut Icon"
    href="{% static 'images/pizza.png' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <title>Smakolyk</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <style>
      body {
        background-image: url('{% static 'images/bg.jpg' %}');
        background-size: cover;
      }
    </style>
{% endblock %}

{% block content %}
    <nav>
        <ul>
            <li><a href="{% url 'smakolyk:welcome' %}"><img src="{% static 'images/pizza.png' %}"></a>
                <a style="color:rgb(127, 24, 24);" href="{% url 'smakolyk:welcome' %}"><h1>SMAKOLYK</h1></a></li>
        </ul>
        <ul>
            {% if user.is_authenticated %}
                <li><a style="color:red;" href="{% url 'smakolyk:order' %}">ORDER</a></li>
                {% if has_order %}
                    <li><a style="color:red;" href="{% url 'smakolyk:history' %}">HISTORY</a></li>
                {% endif %}
                <li><a style="color:red;" href="{% url 'profile' %}">PROFILE</a></li>
            {% endif %}
        </ul>
        <ul>
            {% if user.is_authenticated %}
                <li class="login"><a href="{% url 'logout' %}">LOG OUT</a></li>
            {% else %}
                <li class="login"><a href="{% url 'login' %}">LOG IN</a></li>
                <li class="signup"><a href="{% url 'signup' %}">SIGN UP</a></li>
            {% endif %}
        </ul>
    </nav>
      <div class="main">
        <h1>Menu</h1>
        <div class="first-course">
            <div class="title">
                <h2>First courses</h2>
            </div>
          <div id="carouselExample" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                {% for chunk in menu.first_course %}
                    <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}">
                        <div class="row">
                            {% for item in chunk %}
                                <div class="col-4">
                                    <div class="menu-item">{{ item }}</div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>

            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>
        <div class="second-course">
            <div class="title">
                <h2>Second courses</h2>
            </div>
          <div id="carouselExample2" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              {% for chunk in menu.second_course %}
                    <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}">
                        <div class="row">
                            {% for item in chunk %}
                                <div class="col-4">
                                    <div class="menu-item">{{ item }}</div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
              {% endfor %}
            </div>

            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample2" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample2" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>
          <div class="dessert">
            <div class="title">
                <h2>Desserts</h2>
            </div>
          <div id="carouselExample3" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              {% for chunk in menu.dessert %}
                    <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}">
                        <div class="row">
                            {% for item in chunk %}
                                <div class="col-4">
                                    <div class="menu-item">{{ item }}</div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
              {% endfor %}
            </div>

            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample3" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample3" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>
        <div class="drink">
            <div class="title">
                <h2>Drinks</h2>
            </div>
          <div id="carouselExample4" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              {% for chunk in menu.drink %}
                    <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}">
                        <div class="row">
                            {% for item in chunk %}
                                <div class="col-4">
                                    <div class="menu-item">{{ item }}</div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
              {% endfor %}
            </div>

            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample4" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample4" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>
      </div>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}